### PR TITLE
Add OpenSSF's scorecard

### PR DESCRIPTION
**Pull request by lcarva**

### CODE REVIEW

**Comment by joejstuart** [comment]
How or where do we see the scorecard?

**Comment by lcarva** [comment]
> How or where do we see the scorecard?

https://github.com/orgs/enterprise-contract/security/alerts/code-scanning

Also see our process doc for creating consistency across repos: https://github.com/enterprise-contract/community/blob/main/process/git-repos.md

**Comment by joejstuart** [comment]
> > How or where do we see the scorecard?
> 
> https://github.com/orgs/enterprise-contract/security/alerts/code-scanning
> 
> Also see our process doc for creating consistency across repos: https://github.com/enterprise-contract/community/blob/main/process/git-repos.md

Thanks! I was thrown off by the docs preview comment.

**Review by zregvart — COMMENTED** [review]
Could this be a org-level workflow?

**Comment by lcarva** [comment]
> Could this be a org-level workflow?

Negative. That only applies to workflows that are triggered on pull requests which is not what this is.

**Comment by lcarva** [comment]
Looking for an approval here.

**Review by zregvart — APPROVED** [review]

**Pull request merged**
